//Register,Login.signup
export const LOAD_USER_REGISTER = "LOAD_USER_REGISTER";
export const SUCCESS_USER_REGISTER = "SUCCESS_USER_REGISTER";
export const ERROR_USER_REGISTER = "ERROR_USER_REGISTER";

export const LOAD_USER_LOGIN = "LOAD_USER_LOGIN";
export const SUCCESS_USER_LOGIN = "SUCCESS_USER_LOGIN";
export const ERROR_USER_LOGIN = "ERROR_USER_LOGIN";


export const LOAD_USER_SIGNOUT = "LOAD_USER_SIGNOUT";
export const SUCCESS_USER_SIGNOUT = "SUCCESS_USER_SIGNOUT";
export const ERROR_USER_SIGNOUT = "ERROR_USER_SIGNOUT";

//user crud operation
export const LOAD_GETALL_USER = "LOAD_GETALL_USER";
export const SUCCESS_GETALL_USER = "SUCCESS_GETALL_USER";
export const ERROR_GETALL_USER = "ERROR_GETALL_USER";

export const LOAD_SINGLE_USER = "LOAD_SINGLE_USER";
export const SUCCESS_SINGLE_USER = "SUCCESS_SINGLE_USER";
export const ERROR_SINGLE_USER = "ERROR_SINGLE_USER";

export const LOAD_CREATE_USER = "LOAD_CREATE_USER";
export const SUCCESS_CREATE_USER = "SUCCESS_CREATE_USER";
export const ERROR_CREATE_USER = "ERROR_CREATE_USER";

export const LOAD_UPDATE_USER = "LOAD_UPDATE_USER";
export const SUCCESS_UPDATE_USER = "SUCCESS_UPDATE_USER";
export const ERROR_UPDATE_USER = "ERROR_UPDATE_USER";

export const LOAD_DELETE_USER = "LOAD_DELETE_USER";
export const SUCCESS_DELETE_USER = "SUCCESS_DELETE_USER";
export const ERROR_DELETE_USER = "ERROR_DELETE_USER";


//asset crud operations

export const LOAD_GETALL_ASSET = "LOAD_GETALL_ASSET";
export const SUCCESS_GETALL_ASSET = "SUCCESS_GETALL_ASSET";
export const ERROR_GETALL_ASSET = "ERROR_GETALL_ASSET";

export const LOAD_SINGLE_ASSET = "LOAD_SINGLE_ASSET";
export const SUCCESS_SINGLE_ASSET = "SUCCESS_SINGLE_ASSET";
export const ERROR_SINGLE_ASSET = "ERROR_SINGLE_ASSET";

export const LOAD_CREATE_ASSET = "LOAD_CREATE_ASSET";
export const SUCCESS_CREATE_ASSET = "SUCCESS_CREATE_ASSET";
export const ERROR_CREATE_ASSET = "ERROR_CREATE_ASSET";

export const LOAD_UPDATE_ASSET = "LOAD_UPDATE_ASSET";
export const SUCCESS_UPDATE_ASSET = "SUCCESS_UPDATE_ASSET";
export const ERROR_UPDATE_ASSET = "ERROR_UPDATE_ASSET";

export const LOAD_DELETE_ASSET = "LOAD_DELETE_ASSET";
export const SUCCESS_DELETE_ASSET = "SUCCESS_DELETE_ASSET";
export const ERROR_DELETE_ASSET = "ERROR_DELETE_ASSET";


//request types
export const LOAD_GETALL_REQUEST = "LOAD_GETALL_REQUEST";
export const SUCCESS_GETALL_REQUEST = "SUCCESS_GETALL_REQUEST";
export const ERROR_GETALL_REQUEST = "ERROR_GETALL_REQUEST";

export const LOAD_SINGLE_REQUEST = "LOAD_SINGLE_REQUEST";
export const SUCCESS_SINGLE_REQUEST = "SUCCESS_SINGLE_REQUEST";
export const ERROR_SINGLE_REQUEST = "ERROR_SINGLE_REQUEST";

export const LOAD_CREATE_REQUEST = "LOAD_CREATE_REQUEST";
export const SUCCESS_CREATE_REQUEST = "SUCCESS_CREATE_REQUEST";
export const ERROR_CREATE_REQUEST = "ERROR_CREATE_REQUEST";

export const LOAD_UPDATE_REQUEST = "LOAD_UPDATE_REQUEST";
export const SUCCESS_UPDATE_REQUEST = "SUCCESS_UPDATE_REQUEST";
export const ERROR_UPDATE_REQUEST = "ERROR_UPDATE_REQUEST";

export const LOAD_DELETE_REQUEST = "LOAD_DELETE_REQUEST";
export const SUCCESS_DELETE_REQUEST = "SUCCESS_DELETE_REQUEST";
export const ERROR_DELETE_REQUEST = "ERROR_DELETE_REQUEST";

export const LOAD_REQUEST_STATUS = "LOAD_REQUEST_STATUS";
export const SUCCESS_REQUEST_STATUS = "SUCCESS_REQUEST_STATUS";
export const ERROR_REQUEST_STATUS = "ERROR_REQUEST_STATUS";


//User Assets
export const LOAD_ALLOCATE_ASSET = "LOAD_ALLOCATE_ASSET";
export const SUCCESS_ALLOCATE_ASSET = "SUCCESS_ALLOCATE_ASSET";
export const ERROR_ALLOCATE_ASSET = "ERROR_ALLOCATE_ASSET";

export const LOAD_GETASSIGNED_ASSETS = "LOAD_GETASSIGNED_ASSETS";
export const SUCCESS_GETASSIGNED_ASSETS = "SUCCESS_GETASSIGNED_ASSETS";
export const ERROR_GETASSIGNED_ASSETS = "ERROR_GETASSIGNED_ASSETS";

export const LOAD_UPDATEUSER_ASSET = "LOAD_UPDATEUSER_ASSET";
export const SUCCESS_UPDATEUSER_ASSET = "SUCCESS_UPDATEUSER_ASSET";
export const ERROR_UPDATEUSER_ASSET = "ERROR_UPDATEUSER_ASSET";

export const LOAD_GETUSER_ASSET = "LOAD_GETUSER_ASSET";
export const SUCCESS_GETUSER_ASSET = "SUCCESS_GETUSER_ASSET";
export const ERROR_GETUSER_ASSET = "ERROR_GETUSER_ASSET";


//vendors
export const LOAD_GETALL_VENDOR = "LOAD_GETALL_VENDOR";
export const SUCCESS_GETALL_VENDOR = "SUCCESS_GETALL_VENDOR";
export const ERROR_GETALL_VENDOR = "ERROR_GETALL_VENDOR";

export const LOAD_SINGLE_VENDOR = "LOAD_SINGLE_VENDOR";
export const SUCCESS_SINGLE_VENDOR = "SUCCESS_SINGLE_VENDOR";
export const ERROR_SINGLE_VENDOR = "ERROR_SINGLE_VENDOR";

export const LOAD_CREATE_VENDOR = "LOAD_CREATE_VENDOR";
export const SUCCESS_CREATE_VENDOR = "SUCCESS_CREATE_VENDOR";
export const ERROR_CREATE_VENDOR = "ERROR_CREATE_VENDOR";

export const LOAD_UPDATE_VENDOR = "LOAD_UPDATE_VENDOR";
export const SUCCESS_UPDATE_VENDOR = "SUCCESS_UPDATE_VENDOR";
export const ERROR_UPDATE_VENDOR = "ERROR_UPDATE_VENDOR";

export const LOAD_DELETE_VENDOR = "LOAD_DELETE_VENDOR";
export const SUCCESS_DELETE_VENDOR = "SUCCESS_DELETE_VENDOR";
export const ERROR_DELETE_VENDOR = "ERROR_DELETE_VENDOR";

export const LOAD_REQUEST_VENDOR = "LOAD_REQUEST_VENDOR";
export const SUCCESS_REQUEST_VENDOR = "SUCCESS_REQUEST_VENDOR";
export const ERROR_REQUEST_VENDOR = "ERROR_REQUEST_VENDOR";



export const LOAD_UPDATE_USERPROFILE = "LOAD_UPDATE_USERPROFILE";
export const SUCCESS_UPDATE_USERPROFILE = "SUCCESS_UPDATE_USERPROFILE";
export const ERROR_UPDATE_USERPROFILE = "ERROR_UPDATE_USERPROFILE";


